spring:
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML5
    prefix: classpath:views/
    suffix: .html
  resources:
    static-locations: classpath:/views/

stomp:
  allowed-origins: "*"

server:
  port: 8080